spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USER:hanumanthunani20@gmail.com}
    password: ${EMAIL_PASS}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASS:guest}

rabbitmq:
  queue: email.queue

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
