spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USER:hanumanthubhargav4@gmail.com}
    password: ${EMAIL_PASS}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

rabbitmq:
  queue: email.queue

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
