spring:
  mail:
    host: smtp.gmail.com
    port: 587
    # Uses env var EMAIL_USER, defaults to your email if not found
    username: ${EMAIL_USER:your-email@gmail.com}
    # Uses env var EMAIL_PASS, no default for safety
    password: ${EMAIL_PASS}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASS:guest}

rabbitmq:
  queue: email.queue
